spring:
  application:
    name: global-config
  profiles:
    active: dev
  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
